oos:
  ali:
    accessKey: xxxxxxx
    accessKeySecret: xxxxxxxxxx
    endPoint: niufen-mcp.oss-cn-beijing.aliyuncs.com
    bucketName: niufen-mcp

niufen:
  project:
    name: NiufenProjectName
    port: 1000
    title: ${niufen.project.name}:${niufen.project.port}

spring:
  profiles:
    active: dev
