spring:
  profiles:
    include: druid-multi

mybatis:
  # type-aliases扫描路径
  # type-aliases-package:
  # mapper xml实现扫描路径
  # 具体配置：https://mybatis.org/mybatis-3/zh/configuration.html
  mapper-locations: classpath:mapper/*.xml,classpath:mapper2/*.xml
  config-location: classpath:mybatis-config.xml
logging:
  level:
    io:
      niufen: DEBUG
