spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot_demo?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false
    username: root
    password: 2222
    driver-class-name: com.mysql.jdbc.Driver
# 使用xml方式需要在application.yml中进行一些额外的配置：
mybatis:
  # type-aliases扫描路径
  # type-aliases-package:
  # mapper xml实现扫描路径
  # 具体配置：https://mybatis.org/mybatis-3/zh/configuration.html
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
logging:
  level:
    io:
      niufen: DEBUG
