spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: mall
    password: mall
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot_demo?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false
    username: root
    password: 2222
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    # Redis服务器连接密码（默认为空）
#    password:
    port: 6379
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
# 使用xml方式需要在application.yml中进行一些额外的配置：
mybatis:
  # type-aliases扫描路径
  # type-aliases-package:
  # mapper xml实现扫描路径
  # 具体配置：https://mybatis.org/mybatis-3/zh/configuration.html
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
logging:
  level:
    io:
      niufen: DEBUG
    com: ERROR
    org: ERROR



