#docker build -t swr.cn-north-4.myhuaweicloud.com/joymo-data/alpine-openjdk8-chromedriver:1.0.0 .
FROM swr.cn-north-4.myhuaweicloud.com/joymo-data/alpine-openjdk8-chromedriver:latest
MAINTAINER haijun.zhang
RUN apk add -U tzdata
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

